name: flutter_dev
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # State management
  flutter_bloc: ^8.1.6
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.13
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.4.5
  freezed_annotation: ^2.4.4
  # for dependency injection
  get_it: ^7.6.4
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.9.0
  # Networking
  dio: ^5.3.3
  retrofit: ^4.4.1
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1
  # localization
  intl: ^0.19.0
  easy_localization: ^3.0.7
  # for splash screen
  flutter_native_splash: ^2.4.3
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.16
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/