
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:1097433070650:android:f77bc7498acaa454320903",
        firebase_cli_token: "1//03u0qjUSvZ8fpCgYIARAAGAMSNwF-L9IrIjPRNMvDZHAH2ulM1wSfW5ravikU2w8Z3KxHckYOiPbw_ZIwDuRC_E5MmBW1B2Wgoqw",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "3shmawiii@gmail.com",
        release_notes: "First Fastlane Firebase Distribution Flutter Adv!"
  )
  end
end
